server:
  host: "localhost"
  port: 8080
  ssl: false
  env: "dev"

database:
  postgres:
    host: "localhost"
    port: 5432
    user:
      username: "postgres"
      password: "password"
    database_name: "drifthook"
    options: "sslmode=disable"
    max_open_connection: 15
    max_idle_connection: 12

queue:
  nats:
    urls:
      - "nats://localhost:4222"
    username: ""
    password: ""

storage:
  s3:
    access_key: ""
    secret_key: ""
    bucket_name: ""
    path_prefix: ""
    region: "us-east-1"
    force_path_style: false
    disable_ssl: false
